# Generated by Django 5.0.10 on 2026-04-24 15:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=10, help_text='Order of the model in the UI (smaller number comes first)')),
                ('name', models.CharField(help_text="The model name for calling the LLM API (e.g., gpt-4o-2024-11-20). Check <a href='https://platform.openai.com/docs/models#current-model-aliases' target='_blank'>OpenAI</a>,  <a href='https://docs.anthropic.com/en/docs/about-claude/models' target='_blank'>Anthropic</a>,  <a href='https://console.groq.com/docs/models' target='_blank'>Groq</a>,  <a href='https://api-docs.deepseek.com/quick_start/pricing' target='_blank'>DeepSeek</a>  for model list.", max_length=200)),
                ('display_name', models.CharField(help_text='Display name for the model (e.g., GPT-4o)', max_length=200)),
                ('is_default', models.BooleanField(default=False, help_text='This model will be pre-selected in the UI')),
                ('is_active', models.BooleanField(default=True, help_text='Only active models will be listed in the UI')),
                ('llm_type', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('deepseek', 'DeepSeek'), ('gemini', 'Gemini'), ('custom', 'Custom')], default='openai', help_text='The type of LLM service to use', max_length=20)),
                ('url', models.URLField(blank=True, help_text='URL for custom LLM service (e.g., http://host.docker.internal:8080/v1). Leave empty for OpenAI.', max_length=500, validators=[django.core.validators.URLValidator()])),
            ],
            options={
                'ordering': ['order'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('generic', 'Generic'), ('chat', 'Chat'), ('summarization', 'Summarization'), ('extraction', 'Extraction')], help_text='The purpose of this configuration', max_length=50)),
                ('system_prompt', models.TextField(help_text='The system prompt for the LLM.')),
                ('temperature', models.FloatField(default=0.7, help_text='Value between 0 and 2', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('is_active', models.BooleanField(default=False, help_text='Only one config can be active per purpose')),
                ('model', models.ForeignKey(help_text='The LLM model this config applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_configs', to='llm_caller.llmmodel')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text="API Key (e.g., 'sk-...')", max_length=255)),
                ('name', models.CharField(help_text="A name to identify this key (e.g., 'Primary Key', 'Backup Key')", max_length=100)),
                ('llm_type', models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('deepseek', 'DeepSeek'), ('gemini', 'Gemini'), ('custom', 'Custom')], help_text='The type of LLM service to use', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Only active keys will be used')),
                ('order', models.IntegerField(default=10, help_text='Keys with lower order values will be used first', validators=[django.core.validators.MinValueValidator(0)])),
                ('llm_model', models.ForeignKey(blank=True, help_text='The LLM model this key applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='llm_caller.llmmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuotaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_limit', models.IntegerField(default=10, help_text='Maximum number of requests per day for this model')),
                ('model', models.OneToOneField(help_text='The LLM model this quota applies to', on_delete=django.db.models.deletion.CASCADE, related_name='quota_config', to='llm_caller.llmmodel')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
