# Generated by Django 5.0.10 on 2025-02-09 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_caller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameinteraction',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='llm_caller.gamestory'),
        ),
        migrations.AddField(
            model_name='gamestory',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_stories', to='llm_caller.llmmodel'),
        ),
        migrations.AddField(
            model_name='quotaconfig',
            name='model',
            field=models.OneToOneField(help_text='The LLM model this quota applies to', on_delete=django.db.models.deletion.CASCADE, related_name='quota_config', to='llm_caller.llmmodel'),
        ),
        migrations.AddField(
            model_name='textexplanation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textexplanation',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='llm_caller.gamestory'),
        ),
    ]
