# Generated by Django 5.0.10 on 2025-02-09 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='model',
            field=models.ForeignKey(help_text='The LLM model this config applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_configs', to='llm_caller.llmmodel'),
        ),
    ]
