# Generated by Django 5.0.10 on 2025-02-11 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0003_llmconfig_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='textexplanation',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_explanations', to='llm_caller.llmmodel'),
        ),
    ]
