# Generated by Django 5.0.10 on 2025-02-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0004_textexplanation_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinteraction',
            name='system_input',
        ),
        migrations.RemoveField(
            model_name='gameinteraction',
            name='system_output',
        ),
        migrations.AddField(
            model_name='gameinteraction',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gameinteraction',
            name='role',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='gameinteraction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('aborted', 'Aborted')], default='pending', max_length=20),
        ),
    ]
