# Generated by Django 5.0.10 on 2025-02-24 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0005_remove_gameinteraction_system_input_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestory',
            name='model',
        ),
        migrations.AddField(
            model_name='gamestory',
            name='cefr_level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', help_text='CEFR level of the story (e.g., A1, B2)', max_length=10),
        ),
        migrations.AddField(
            model_name='gamestory',
            name='details',
            field=models.TextField(blank=True, help_text='Additional details of the story (generated or user-provided)'),
        ),
        migrations.AddField(
            model_name='gamestory',
            name='scene_text',
            field=models.TextField(blank=True, help_text='Scene text of the story (generated or user-provided)'),
        ),
        migrations.AlterField(
            model_name='gameinteraction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('streaming', 'Streaming'), ('completed', 'Completed'), ('failed', 'Failed'), ('aborted', 'Aborted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamestory',
            name='status',
            field=models.CharField(choices=[('INIT', 'Init'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='INIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='purpose',
            field=models.CharField(choices=[('scene_generation', 'Scene Generation'), ('adventure_gameplay', 'Adventure Gameplay'), ('text_explanation', 'Text Explanation'), ('story_skeleton_generation', 'Story Skeleton Generation'), ('story_continuation', 'Story Continuation'), ('story_ending', 'Story Ending'), ('cefr_check', 'CEFR Level Check')], help_text='The purpose of this configuration', max_length=50),
        ),
        migrations.CreateModel(
            name='StoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('decision_point_id', models.CharField(blank=True, max_length=50)),
                ('chosen_option_id', models.CharField(blank=True, max_length=50)),
                ('is_end_point', models.BooleanField(default=False)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='llm_caller.gamestory')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorySkeleton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background', models.TextField()),
                ('raw_data', models.JSONField()),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skeleton', to='llm_caller.gamestory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
