# Generated by Django 5.0.10 on 2025-02-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0006_remove_gamestory_model_gamestory_cefr_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyprogress',
            name='chosen_option_text',
            field=models.TextField(blank=True),
        ),
    ]
