# Generated by Django 5.0.10 on 2025-02-24 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0007_storyprogress_chosen_option_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_id', models.CharField(max_length=50)),
                ('option_name', models.TextField()),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='llm_caller.storyprogress')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
