# Generated by Django 5.0.10 on 2025-02-24 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0008_storyoption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameInteraction',
        ),
    ]
