# Generated by Django 5.0.10 on 2025-02-24 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0009_delete_gameinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='llm_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('custom', 'Custom')], default='openai', help_text='The type of LLM service to use', max_length=20),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='url',
            field=models.URLField(blank=True, help_text='URL for custom LLM service (e.g., http://host.docker.internal:8080/v1). Leave empty for OpenAI.', max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
    ]
