# Generated by Django 5.0.10 on 2025-02-24 22:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0010_llmmodel_llm_type_llmmodel_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text="API Key (e.g., 'sk-...')", max_length=255)),
                ('name', models.CharField(help_text="A name to identify this key (e.g., 'Primary Key', 'Backup Key')", max_length=100)),
                ('llm_type', models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('custom', 'Custom')], help_text='The type of LLM service to use', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Only active keys will be used')),
                ('order', models.IntegerField(default=10, help_text='Keys with lower order values will be used first', validators=[django.core.validators.MinValueValidator(0)])),
                ('llm_model', models.ForeignKey(help_text='The LLM model this key applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='llm_caller.llmmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='OpenAIKey',
        ),
    ]
