# Generated by Django 5.0.10 on 2025-02-24 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0011_apikey_delete_openaikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='llm_model',
            field=models.ForeignKey(blank=True, help_text='The LLM model this key applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='llm_caller.llmmodel'),
        ),
    ]
