# Generated by Django 5.0.10 on 2025-02-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0012_alter_apikey_llm_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='llm_type',
            field=models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('custom', 'Custom')], help_text='The type of LLM service to use', max_length=20),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='llm_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('custom', 'Custom')], default='openai', help_text='The type of LLM service to use', max_length=20),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='name',
            field=models.CharField(help_text="The model name for calling the LLM API (e.g., gpt-4o-2024-11-20). Check <a href='https://platform.openai.com/docs/models#current-model-aliases' target='_blank'>OpenAI</a>,  <a href='https://docs.anthropic.com/en/docs/about-claude/models' target='_blank'>Anthropic</a>,  <a href='https://console.groq.com/docs/models' target='_blank'>Groq</a>  for model list.", max_length=200),
        ),
    ]
