# Generated by Django 5.0.10 on 2025-02-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0013_alter_apikey_llm_type_alter_llmmodel_llm_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyskeleton',
            name='status',
            field=models.CharField(choices=[('INIT', 'Init'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='INIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='llm_type',
            field=models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('deepseek', 'DeepSeek'), ('custom', 'Custom')], help_text='The type of LLM service to use', max_length=20),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='purpose',
            field=models.CharField(choices=[('scene_generation', 'Scene Generation'), ('text_explanation', 'Text Explanation'), ('story_skeleton_generation', 'Story Skeleton Generation'), ('story_continuation', 'Story Continuation'), ('story_ending', 'Story Ending')], help_text='The purpose of this configuration', max_length=50),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='llm_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('deepseek', 'DeepSeek'), ('custom', 'Custom')], default='openai', help_text='The type of LLM service to use', max_length=20),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='name',
            field=models.CharField(help_text="The model name for calling the LLM API (e.g., gpt-4o-2024-11-20). Check <a href='https://platform.openai.com/docs/models#current-model-aliases' target='_blank'>OpenAI</a>,  <a href='https://docs.anthropic.com/en/docs/about-claude/models' target='_blank'>Anthropic</a>,  <a href='https://console.groq.com/docs/models' target='_blank'>Groq</a>,  <a href='https://api-docs.deepseek.com/quick_start/pricing' target='_blank'>DeepSeek</a>  for model list.", max_length=200),
        ),
        migrations.AlterField(
            model_name='storyskeleton',
            name='background',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storyskeleton',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
