# Generated by Django 5.0.10 on 2025-08-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0014_storyskeleton_status_alter_apikey_llm_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamestory',
            options={'verbose_name_plural': 'Game stories'},
        ),
        migrations.AlterModelOptions(
            name='storyoption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='storyprogress',
            options={},
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='purpose',
            field=models.CharField(choices=[('scene_generation', 'Scene Generation'), ('scene_generation_demo', 'Scene Generation (Demo)'), ('text_explanation', 'Text Explanation'), ('text_explanation_demo', 'Text Explanation (Demo)'), ('story_skeleton_generation', 'Story Skeleton Generation'), ('story_skeleton_generation_demo', 'Story Skeleton Generation (Demo)'), ('story_continuation', 'Story Continuation'), ('story_continuation_demo', 'Story Continuation (Demo)'), ('story_ending', 'Story Ending'), ('story_ending_demo', 'Story Ending (Demo)')], help_text='The purpose of this configuration', max_length=50),
        ),
    ]
