# Generated by Django 5.0.10 on 2025-12-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0016_storyprogress_summary_alter_llmconfig_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyprogress',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='storyskeleton',
            name='stock_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='llm_type',
            field=models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('deepseek', 'DeepSeek'), ('gemini', 'Gemini'), ('custom', 'Custom')], help_text='The type of LLM service to use', max_length=20),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='purpose',
            field=models.CharField(choices=[('scene_generation', 'Scene Generation'), ('scene_generation_demo', 'Scene Generation (Demo)'), ('text_explanation', 'Text Explanation'), ('text_explanation_demo', 'Text Explanation (Demo)'), ('story_skeleton_generation', 'Story Skeleton Generation'), ('story_skeleton_generation_demo', 'Story Skeleton Generation (Demo)'), ('story_continuation', 'Story Continuation'), ('story_continuation_demo', 'Story Continuation (Demo)'), ('story_ending', 'Story Ending'), ('story_ending_demo', 'Story Ending (Demo)'), ('story_summary', 'Story Summary'), ('image_generation', 'Image Generation'), ('image_generation_demo', 'Image Generation (Demo)')], help_text='The purpose of this configuration', max_length=50),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='llm_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('deepseek', 'DeepSeek'), ('gemini', 'Gemini'), ('custom', 'Custom')], default='openai', help_text='The type of LLM service to use', max_length=20),
        ),
    ]
