# Generated by Django 5.0.10 on 2026-01-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0017_storyprogress_image_url_storyskeleton_stock_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestory',
            name='theme',
            field=models.TextField(blank=True, help_text='Theme of the story (e.g., friendship, loyalty)'),
        ),
    ]
