# Generated by Django 5.0.10 on 2026-01-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0018_gamestory_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestory',
            name='cefr_level',
        ),
        migrations.AddField(
            model_name='gamestory',
            name='language_level',
            field=models.CharField(default='', help_text='Language level of the story (e.g., A1, B2)', max_length=10),
            preserve_default=False,
        ),
    ]
