# Generated by Django 5.0.10 on 2026-01-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0019_remove_gamestory_cefr_level_gamestory_language_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyskeleton',
            name='character_base_images',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
