# Generated by Django 5.0.10 on 2026-04-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0020_storyskeleton_character_base_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='purpose',
            field=models.CharField(choices=[('scene_generation', 'Scene Generation'), ('scene_generation_demo', 'Scene Generation (Demo)'), ('text_explanation', 'Text Explanation'), ('text_explanation_demo', 'Text Explanation (Demo)'), ('story_skeleton_generation', 'Story Skeleton Generation'), ('story_skeleton_generation_demo', 'Story Skeleton Generation (Demo)'), ('story_continuation', 'Story Continuation'), ('story_continuation_demo', 'Story Continuation (Demo)'), ('story_ending', 'Story Ending'), ('story_ending_demo', 'Story Ending (Demo)'), ('story_summary', 'Story Summary'), ('image_generation', 'Image Generation'), ('image_generation_demo', 'Image Generation (Demo)'), ('vocabulary_quiz', 'Vocabulary Quiz Evaluation'), ('vocabulary_quiz_demo', 'Vocabulary Quiz Evaluation (Demo)')], help_text='The purpose of this configuration', max_length=50),
        ),
    ]
