# Generated by Django 5.0.10 on 2026-04-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0023_remove_text_game_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='purpose',
            field=models.CharField(choices=[('generic', 'Generic'), ('chat', 'Chat'), ('summarization', 'Summarization'), ('extraction', 'Extraction')], help_text='The purpose of this configuration', max_length=50),
        ),
    ]
