# Generated by Django 5.0.10 on 2026-04-24 00:00

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("topic", models.CharField(blank=True, default="", max_length=500)),
                ("turn_count", models.IntegerField(default=0)),
                ("previous_speaker", models.CharField(blank=True, max_length=100, null=True)),
                ("pending_forced_user_turn", models.BooleanField(default=False)),
                ("terminate", models.BooleanField(default=False)),
                ("max_turns", models.IntegerField(default=12)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent_id", models.CharField(max_length=100)),
                ("personality", models.JSONField(blank=True, default=dict)),
                ("traits", models.JSONField(blank=True, default=dict)),
                ("voice", models.CharField(blank=True, default="", max_length=100)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_profiles",
                        to="conversation.conversationsession",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "agent_id")},
            },
        ),
        migrations.CreateModel(
            name="TurnRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("speaker", models.CharField(max_length=100)),
                (
                    "speaker_type",
                    models.CharField(
                        choices=[("user", "User"), ("agent", "Agent"), ("makeshift", "Makeshift")],
                        max_length=20,
                    ),
                ),
                ("utterance", models.TextField()),
                ("speech_act", models.CharField(blank=True, default="", max_length=50)),
                ("subtype", models.CharField(blank=True, max_length=50, null=True)),
                ("target", models.CharField(blank=True, max_length=200, null=True)),
                ("turn_index", models.IntegerField()),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                ("audio_url", models.URLField(blank=True, max_length=1000, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="conversation.conversationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["turn_index"],
                "unique_together": {("session", "turn_index")},
            },
        ),
    ]

