# Generated by Django 5.0.10 on 2026-04-24 00:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationsession",
            name="paused",
            field=models.BooleanField(default=False),
        ),
    ]

