# Generated by GPT-5.2 on 2026-04-29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0004_conversationllmprompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="turnrecord",
            name="subturn_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelOptions(
            name="turnrecord",
            options={"ordering": ["turn_index", "subturn_index"]},
        ),
        migrations.AlterUniqueTogether(
            name="turnrecord",
            unique_together={("session", "turn_index", "subturn_index")},
        ),
    ]

