# Generated by GPT-5.2 on 2026-04-29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0005_turnrecord_subturn_index_and_makeshift_appendix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationsession",
            name="max_turns",
            field=models.IntegerField(default=50),
        ),
    ]

