# Generated by GPT-5.2 on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0006_conversationsession_max_turns_default_50"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]

