# Generated by Django 5.0.10 on 2026-05-06 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0010_conversationsession_agent_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('source_uri', models.CharField(blank=True, default='', max_length=1000)),
                ('source_label', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TurnRetrieval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.TextField(blank=True, default='')),
                ('requested_sources', models.JSONField(blank=True, default=list)),
                ('source_statuses', models.JSONField(blank=True, default=dict)),
                ('items', models.JSONField(blank=True, default=list)),
                ('rendered_context', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_traces', to='conversation.turnrecord')),
            ],
            options={
                'ordering': ['turn_id', 'id'],
            },
        ),
    ]
