# Generated by Codex on 2026-05-08

from django.db import migrations, models
from pgvector.django import HnswIndex
from pgvector.django import VectorExtension
from pgvector.django import VectorField


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0011_knowledge_snippet_turn_retrieval"),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name="knowledgesnippet",
            name="embedding",
            field=VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name="knowledgesnippet",
            name="embedding_model",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="knowledgesnippet",
            name="embedding_dimensions",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgesnippet",
            name="embedding_text_hash",
            field=models.CharField(blank=True, default="", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="knowledgesnippet",
            name="embedding_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="knowledgesnippet",
            index=HnswIndex(
                name="conv_know_emb_hnsw",
                fields=["embedding"],
                m=16,
                ef_construction=64,
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
