# Generated by Django 5.0.10 on 2026-05-08 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0012_knowledge_snippet_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnEngineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.CharField(choices=[('turn_manager', 'Turn manager'), ('turn_processor', 'Turn processor')], max_length=40)),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], default='INFO', max_length=10)),
                ('event', models.CharField(blank=True, default='', max_length=120)),
                ('message', models.TextField(blank=True, default='')),
                ('context', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('turn_index', models.IntegerField(blank=True, null=True)),
                ('subturn_index', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_engine_logs', to='conversation.conversationsession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['session', '-created_at'], name='conv_telog_session_ts'), models.Index(fields=['session', 'component', '-created_at'], name='conv_telog_comp_ts'), models.Index(fields=['session', 'level', '-created_at'], name='conv_telog_level_ts')],
            },
        ),
    ]
