# Generated by ChatGPT on 2026-05-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import backend.conversation.models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0013_turnenginelog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAudio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("audio_file", models.FileField(upload_to=backend.conversation.models.user_audio_upload_to)),
                ("content_type", models.CharField(blank=True, default="", max_length=100)),
                ("original_filename", models.CharField(blank=True, default="", max_length=255)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_audios",
                        to="conversation.conversationsession",
                    ),
                ),
                (
                    "turn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_audios",
                        to="conversation.turnrecord",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_user_audios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="useraudio",
            index=models.Index(fields=["session", "-created_at"], name="conv_ua_session_ts"),
        ),
        migrations.AddIndex(
            model_name="useraudio",
            index=models.Index(fields=["user", "-created_at"], name="conv_ua_user_ts"),
        ),
    ]

