# Generated by Codex on 2026-05-13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from pgvector.django import HnswIndex
from pgvector.django import VectorField


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0014_useraudio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMemory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("memory_type", models.CharField(blank=True, default="profile", max_length=100)),
                ("source_uri", models.CharField(blank=True, default="", max_length=1000)),
                ("source_label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("embedding", VectorField(blank=True, dimensions=1536, null=True)),
                ("embedding_model", models.CharField(blank=True, default="", max_length=100, null=True)),
                ("embedding_dimensions", models.PositiveIntegerField(blank=True, null=True)),
                ("embedding_text_hash", models.CharField(blank=True, default="", max_length=64, null=True)),
                ("embedding_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="long_term_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user_id", "memory_type", "id"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active", "memory_type"],
                        name="conv_um_user_active_type_idx",
                    ),
                    HnswIndex(
                        name="conv_user_mem_emb_hnsw",
                        fields=["embedding"],
                        m=16,
                        ef_construction=64,
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
            },
        ),
    ]
