# Generated by Django 5.1 on 2026-05-17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0015_usermemory"),
    ]

    operations = [
        migrations.AddField(
            model_name="turnrecord",
            name="duplicate_similarity_score",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="turnrecord",
            name="duplicate_is_repetition",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="turnrecord",
            name="duplicate_threshold",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="turnrecord",
            name="duplicate_matched_turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicate_matches",
                to="conversation.turnrecord",
            ),
        ),
        migrations.AddField(
            model_name="turnrecord",
            name="duplicate_matched_utterance",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="turnrecord",
            name="duplicate_matched_speaker",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="turnrecord",
            name="duplicate_matched_turn_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="turnrecord",
            name="duplicate_matched_subturn_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="turnrecord",
            name="duplicate_reason",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
