# Generated by Django 5.0.10 on 2026-05-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0016_turnrecord_duplicate_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnrecord',
            name='utterance_tts',
            field=models.TextField(blank=True, default='', help_text='Agent-only: text sent to the TTS provider, with audio tags preserved. Empty for user turns.'),
        ),
    ]
