# Generated by Django 5.0.10 on 2026-06-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0021_turnrecord_lipsync'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exemplar',
            options={'ordering': ['title', 'id'], 'verbose_name': 'Exemplar', 'verbose_name_plural': 'Exemplars'},
        ),
    ]
