# Generated by Django 5.0.10 on 2026-06-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0023_sessionnewschunk_web_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangMemMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'LangMem memory',
                'verbose_name_plural': 'LangMem memories',
                'managed': False,
            },
        ),
    ]
