# Generated by Django 5.0.10 on 2026-06-03 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('miniflux_entry_id', models.PositiveBigIntegerField(unique=True)),
                ('miniflux_feed_id', models.PositiveBigIntegerField()),
                ('feed_title', models.CharField(max_length=255)),
                ('source_title', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True, default='')),
                ('url', models.URLField(max_length=1000)),
                ('normalized_url', models.URLField(max_length=1000, unique=True)),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('hidden', 'Hidden')], default='imported', max_length=32)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-published_at', '-id'),
                'indexes': [models.Index(fields=['status', '-published_at'], name='news_article_status_pub_idx'), models.Index(fields=['miniflux_feed_id', '-published_at'], name='news_article_feed_pub_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxonomy_version', models.CharField(max_length=32)),
                ('main_category', models.CharField(blank=True, max_length=100)),
                ('subtopics', models.JSONField(blank=True, default=list)),
                ('cefr_level', models.CharField(blank=True, max_length=8)),
                ('is_suitable', models.BooleanField(default=False)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('llm_model', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], default='succeeded', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='news.newsarticle')),
            ],
            options={
                'ordering': ('-classified_at', '-id'),
                'indexes': [models.Index(fields=['taxonomy_version', 'main_category', 'status', 'is_suitable'], name='news_class_lookup_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='newsclassification',
            constraint=models.UniqueConstraint(fields=('article', 'taxonomy_version'), name='unique_news_classification_per_taxonomy'),
        ),
    ]
