# Generated by GPT-5.2 on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile_profile_completed_and_cefr_samples"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="preferred_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="How the user would like to be addressed in the conversation.",
                max_length=80,
            ),
        ),
    ]

