# Generated by Django 5.0.10 on 2025-08-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_demo_account',
            field=models.BooleanField(default=False, help_text='Whether this is a demo account that should use demo prompts'),
        ),
    ]
