# Generated by Django 5.0.10 on 2026-04-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_is_demo_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='native_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French'), ('ja', 'Japanese'), ('zh', 'Chinese')], help_text='Language used for word explanations and UI copy where relevant.', max_length=10, null=True, verbose_name='Native language'),
        ),
    ]
