# Generated by Django 5.0.10 on 2026-04-24 00:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_userprofile_native_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ocean",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="OCEAN self-evaluation levels, e.g. {'openness': 'high', ...}.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="cefr_level",
            field=models.CharField(
                blank=True,
                default="",
                help_text="CEFR level (e.g., A1, A2, B1, B2, C1, C2).",
                max_length=10,
            ),
        ),
    ]

