# Generated by Django 5.0.10 on 2026-04-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_ocean_cefr_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='native_language',
        ),
    ]
